---
convention:
  commitTypes:
    - feat
    - fix
    - perf
    - refactor
    - style
    - test
    - build
    - ops
    - docs
    - merge
  commitScopes: []
  releaseTagGlobPattern: v[0-9]*.[0-9]*.[0-9]*

changelog:
  commitTypes:
    - feat
    - fix
    - perf
    - merge
  includeInvalidCommits: true
  commitScopes: []
  commitIgnoreRegexPattern: "^WIP "
  headlines:
    feat: Features
    fix: Bug Fixes
    perf: Performance Improvements
    merge: Merges
    breakingChange: BREAKING CHANGES
