[project]
name = "marshmallow-peewee"
version = "5.0.0"
description = "Peewee ORM integration with the Marshmallow (de)serialization library"
authors = [{ name = "Kirill Klenov", email = "horneds@gmail.com" }]
requires-python = ">=3.10,<4"
readme = "README.md"
license = "MIT"
keywords = ["marshmallow", "peewee", "orm", "serialization", "deserialization"]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]
dependencies = ["peewee", "marshmallow>=3.0.0,<4"]

[project.urls]
Homepage = "https://github.com/klen/marshmallow-peewee"
Repository = "https://github.com/klen/marshmallow-peewee"

[dependency-groups]
dev = ["pre-commit", "ruff", "pyrefly"]
tests = ["pytest"]

[tool.uv]
default-groups = "all"

[tool.uv.build-backend]
module-name = ["marshmallow_peewee"]
module-root = ""

[build-system]
requires = ["uv_build>=0.10.2,<0.11.0"]
build-backend = "uv_build"

[tool.pytest.ini_options]
addopts = "-xvs"

[tool.ruff]
include = ["marshmallow_peewee/*", "tests/**/*"]
line-length = 100
target-version = "py310"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "ANN",
  "ARG",
  "COM",
  "D",
  "N",
  "UP",
  "S",
  "SLF",
  "INP001",
  "PLR2004",
  "TD",
  "FIX",
]

[tool.pyrefly]
project-includes = ["marshmallow_peewee"]
project-excludes = ["tests", "pyproject.toml"]

[tool.bumpversion]
current_version = "5.0.0"
commit = false
tag = false

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'
