name: publish

on:
  workflow_run:
    workflows: [tests]
    branches: [master]
    types: [completed]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - name: Build and publish to pypi
      uses: JRubics/poetry-publish@v1.16
      with:
        pypi_token: ${{ secrets.PYPI }}

  notify:
    runs-on: ubuntu-latest
    needs: release
    steps:

    - name: Notify Success
      uses: archive/github-actions-slack@master
      with:
          slack-channel: C2CRL4C4V
          slack-text: Build is success *[${{ github.repository }}] (${{ github.ref }})* https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack-optional-as_user: false
          slack-optional-icon_emoji: ":white_check_mark:"
